#!/bin/bash

hostnamectl set-hostname nextcloud
sed -i 's/x6/nextcloud/g'

umount /var/www/html
chgrp vboxsf /var/www
apt install -y apache2 postgresql php curl unzip
usermod -aG vboxsf www-data
sed -i 's/nss-lookup.target/nss-lookup.target vboxadd.service vboxadd-service.service/g' /lib/systemd/system/apache2.service
apt install -y php-{gd,curl,zip,pgsql,xml,mbstring}
chown www-data /var/www/html
service apache2 restart

pushd /var/www
mv ~/nextcloud/nextcloud.z?? .
unzip nextcloud.zip
rm -rf html
mv nextcloud html
chown -R www-data html
cd html
sudo -u www-data php occ maintenance:install --database "pgsql" --database-name "nextcloud" --database-user "nextcloud" --database-pass "nextcloud" --admin-user "admin" --admin-pass "admin"
sleep 15
grep -v ");" config/config.php > config/config2.php
echo ");" >> config/config2.php
mv config/config2.php config/config.php
chown www-data config/config.php
cat config/config.php
sleep 15
popd

#wget https://download.nextcloud.com/server/installer/setup-nextcloud.php -O /var/www/html/setup.php
#chmod 755 /var/www/html/setup.php

echo enp0s3: \\4{enp0s3} >> /etc/issue
echo enp0s8: \\4{enp0s8} >> /etc/issue
echo "" >> /etc/issue

echo "net.ipv4.ip_forward=0" > /etc/sysctl.conf
echo "net.ipv4.conf.default.rp_filter=1" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.rp_filter=1" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.accept_redirects=0" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.secure_redirects=0" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.accept_source_route=0" >> /etc/sysctl.conf

echo tail -f /var/log/apache2/*.log > ~/bin/view_logs
chmod +x ~/bin/view_logs

iptables -F
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -A INPUT -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m state --state NEW -p tcp --dport 80 -j ACCEPT
iptables-save > /etc/firewall

echo "#! /bin/bash" > /etc/network/if-pre-up.d/iptables
echo "" >> /etc/network/if-pre-up.d/iptables
echo "iptables-restore < /etc/firewall" >> /etc/network/if-pre-up.d/iptables
chmod +x /etc/network/if-pre-up.d/iptables

sudo -i -u postgres psql -c "CREATE DATABASE nextcloud;"
sudo -i -u postgres psql -c "CREATE USER nextcloud WITH password 'nextcloud';"
sudo -i -u postgres psql -c "GRANT ALL privileges ON DATABASE nextcloud TO nextcloud;"

#CREATE USER nextcloud WITH PASSWORD 'nextcloud';
#CREATE DATABASE nextcloud TEMPLATE template0 ENCODING 'UNICODE';
#ALTER DATABASE nextcloud OWNER TO nextcloud;
#GRANT ALL PRIVILEGES ON DATABASE nextcloud TO nextcloud;

function eof {
  cd;
  rm -rf ~/nextcloud;
  systemctl reboot;
}

trap eof EXIT
